// Generated by scripts/prepare-brand-assets.mjs. Paths are relative to the configured site base.
export const brand = {
  name: 'TheJobPoolConsultants',
  descriptor: 'Blogs · Knowledge Hub',
  favicon: 'brand/mark.svg',
  assets: {
    logo: {
      src: 'brand/thejobpoolconsultants/knowledge-hub/logos/thejobpoolconsultants-knowledge-hub-light.png',
      width: 768,
      height: 317,
      small: {
        src: 'brand/thejobpoolconsultants/knowledge-hub/logos/thejobpoolconsultants-knowledge-hub-light-384.png',
        width: 384,
        height: 159,
      },
    },
    darkLogo: {
      src: 'brand/thejobpoolconsultants/knowledge-hub/logos/thejobpoolconsultants-knowledge-hub-dark.png',
      width: 768,
      height: 317,
      small: {
        src: 'brand/thejobpoolconsultants/knowledge-hub/logos/thejobpoolconsultants-knowledge-hub-dark-384.png',
        width: 384,
        height: 159,
      },
    },
    emblem: {
      src: 'brand/thejobpoolconsultants/knowledge-hub/emblems/thejobpoolconsultants-knowledge-hub-emblem.png',
      width: 320,
      height: 315,
      small: {
        src: 'brand/thejobpoolconsultants/knowledge-hub/emblems/thejobpoolconsultants-knowledge-hub-emblem-96.png',
        width: 96,
        height: 95,
      },
    },
    intelligenceBanner: {
      src: 'brand/thejobpoolconsultants/knowledge-hub/banners/thejobpoolconsultants-understand-intelligence-banner.webp',
      width: 1600,
      height: 900,
      medium: {
        src: 'brand/thejobpoolconsultants/knowledge-hub/banners/thejobpoolconsultants-understand-intelligence-banner-960.webp',
        width: 960,
        height: 540,
      },
      mobile: {
        src: 'brand/thejobpoolconsultants/knowledge-hub/banners/thejobpoolconsultants-understand-intelligence-banner-visual-mobile.webp',
        width: 768,
        height: 673,
      },
    },
    publicationBanner: {
      src: 'brand/thejobpoolconsultants/knowledge-hub/banners/thejobpoolconsultants-blogs-knowledge-hub-banner.webp',
      width: 1600,
      height: 533,
      medium: {
        src: 'brand/thejobpoolconsultants/knowledge-hub/banners/thejobpoolconsultants-blogs-knowledge-hub-banner-960.webp',
        width: 960,
        height: 320,
      },
      mobile: {
        src: 'brand/thejobpoolconsultants/knowledge-hub/banners/thejobpoolconsultants-blogs-knowledge-hub-banner-visual-mobile.webp',
        width: 768,
        height: 367,
      },
    },
    social: {
      src: 'brand/thejobpoolconsultants/knowledge-hub/social/thejobpoolconsultants-knowledge-hub-social-card.png',
      width: 1200,
      height: 630,
    },
  },
} as const;
